version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-cmpc_libros}
      POSTGRES_USER: ${DB_USER:-cmpc}
      POSTGRES_PASSWORD: ${DB_PASS:-cmpc_password}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      DB_HOST: postgres
    ports:
      - "3000:3000"
    command: sh -c "npm run migrate && node dist/main.js"

volumes:
  pgdata:
